### ISSUE TITLE
如何添加网络层

### ISSUE THREAD

**Issue by zhuasd** [bubbliiiing/efficientnet-yolo3-pytorch#17]
如何添加第四层网络特征层呢？

一直报下面的错误：
   self.last_layer3_conv       = conv2d(out_filters[-3], out_filters[-4], 1)
IndexError: list index out of range
root@2f0cdf9ef68c:/home/zzg/yolo3-efficientnet# python3 train.py
Traceback (most recent call last):
  File "train.py", line 271, in <module>
    model = YoloBody(anchors_mask, num_classes, phi=phi, load_weights=pretrained)
  File "/home/zzg/yolo3-efficientnet/nets/yolo.py", line 99, in __init__
    self.last_layer3_conv       = conv2d(out_filters[-3], out_filters[-4], 1)
IndexError: list index out of range
root@2f0cdf9ef68c:/home/zzg/yolo3-efficientnet# 

这是我修改网络的片段：

        out_filters = {
            0: [40, 112, 320],
            1: [40, 112, 320],
            2: [48, 120, 352],
            3: [48, 136, 384],
            4: [56, 160, 448],
            5: [64, 176, 512],
            6: [72, 200, 576],
            7: [80, 224, 640],
        }[phi]

        self.last_layer0            = make_last_layers([out_filters[-1], int(out_filters[-1]*2)], out_filters[-1], len(anchors_mask[0]) * (num_classes + 5))

        self.last_layer1_conv       = conv2d(out_filters[-1], out_filters[-2], 1)
        self.last_layer1_upsample   = nn.Upsample(scale_factor=2, mode='nearest')
        self.last_layer1            = make_last_layers([out_filters[-2], int(out_filters[-2]*2)], out_filters[-2] + out_filters[-2], len(anchors_mask[1]) * (num_classes + 5))

        self.last_layer2_conv       = conv2d(out_filters[-2], out_filters[-3], 1)
        self.last_layer2_upsample   = nn.Upsample(scale_factor=2, mode='nearest')
        self.last_layer2            = make_last_layers([out_filters[-3], int(out_filters[-3]*2)], out_filters[-3] + out_filters[-3], len(anchors_mask[2]) * (num_classes + 5))

        self.last_layer3_conv       = conv2d(out_filters[-3], out_filters[-4], 1)
        self.last_layer3_upsample   = nn.Upsample(scale_factor=2, mode='nearest')
        self.last_layer3            = make_last_layers([out_filters[-4], int(out_filters[-4]*2)], out_filters[-4] + out_filters[-4], len(anchors_mask[3]) * (num_classes + 5))

**Comment by bubbliiiing** [comment]
额……-4在哪里
